language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO=django==3.1
  - DJANGO=django==4.0
  - DJANGO=django==4.1

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to install dependencies
install:
  - pip install -r tests/requirements/py3.txt
  - pip install -e .
  - pip install $DJANGO
  - pip install codecov

script:
  - cd tests/
  - coverage run runtests.py

after_success:
  - codecov
