# Generated by Django 6.0.3 on 2026-06-19 05:46

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200711_1253'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='myactivity',
            options={'verbose_name': 'My Activity', 'verbose_name_plural': 'My Activities'},
        ),
    ]
